pipelineJob(pipeline-code-job) {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    echo 'Build succeeded'
                    archiveArtifacts '**/*.war'
                }
            }
        }
    }
} 
