pipelineJ{
    agent any
    stages {
        stage('build') {
            steps {
                sh 'mvn -f  java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo 'Build succeeded'
                    archiveArtifacts '**/*.war'
                }
            }
        }
    }
} 
